### ISSUE TITLE
Flap timer Gecko Code

### ISSUE THREAD

**Issue by malleoz** [TASLabz/dolphin-lua-core#13]
Show a flap timer on-screen.

To be developed by _tZ

**Comment by ximk** [comment]
https://mariokartwii.com/showthread.php?tid=1978

Unless we find a way to manipulate the in-game timer to display the lap 2 timer, this is going to be the most accurate way of timing flaps. Users should be notified that this code is not 100% accurate, and should disable the code for official timing purposes.
