### ISSUE TITLE
Remove Qt dependency

### ISSUE THREAD

**Issue by malleoz** [TASLabz/dolphin-lua-core#24]
The version of Dolphin this repo is based off of still uses Wx, even though there are some Qt components.

- [x] Verify the claim I made above is true
- [x] Remove all dependencies

**Comment by vabold** [comment]
Claim verified by Billiard via Dolphin discord.

**Comment by malleoz** [comment]
PR here: https://github.com/TASLabz/dolphin-lua-core/pull/30
Issue will be closed when this is merged.

**Comment by vabold** [comment]
Resolved in https://github.com/TASLabz/dolphin-lua-core/commit/d5b0f9ee0ef03881a04480d60a7337267785c9d4.
