### ISSUE TITLE
Revert Dolphin InfoDisplay to only include basic info

### ISSUE THREAD

**Issue by malleoz** [TASLabz/dolphin-lua-core#4]
You don't need every bit of available info if you're doing something super basic, so we shouldn't always include it in Dolphin. The complicated info should just be available in the external InfoDisplay.

**Comment by ximk** [comment]
The team has agreed that an external info display program is not needed at the moment, meaning this won't be necessary for the forseeable future. When the team feels it is necessary, this issue will be reopened.
