### ISSUE TITLE
Multiple controllers + WiiMote Lua support

### ISSUE THREAD

**Issue by malleoz** [TASLabz/dolphin-lua-core#5]
Xander has implemented support for multiple controllers via Lua, and also the ability to control WiiMotes via Lua. Implement that functionality in this branch too.

https://github.com/MikeXander/Dolphin-Lua-Core

**Comment by malleoz** [comment]
When I am done, support will still need to be added for Classic Controller. As Xander puts it best: "because I'm lazy and don't know anyone who TASes with it"

**Comment by malleoz** [comment]
PR opened here https://github.com/TASLabz/dolphin-lua-core/pull/22

**Comment by vabold** [comment]
Resolved in https://github.com/TASLabz/dolphin-lua-core/commit/36cb1edc4542b8976ac7dca92726122eebe96bab.
