### ISSUE TITLE
Exact Finish Display

### ISSUE THREAD

**Issue by malleoz** [TASLabz/dolphin-lua-core#9]
Show a more accurate finish time using stebler's Gecko Code which caches the un-rounded finish time.

**Comment by ximk** [comment]
This is now complete and will be addressed in a future PR with all the scripts that are planned to be released on the target release date, 12/31 (or prior if the team feels satisfied with the progress). Additional enhancements would be nice to remove a minor issue with the display currently, but this would require both a gecko code that would have to be made from scratch and knowledge the community does not yet have.
